// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGu5yyftI27UxVAkUinMGJ1sfFbZnUVnE',
    appId: '1:499282073775:web:1a57c969bfad0269b55c5a',
    messagingSenderId: '499282073775',
    projectId: 'chat-app-553db',
    authDomain: 'chat-app-553db.firebaseapp.com',
    storageBucket: 'chat-app-553db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsByz4VgwcxXDPbaJPBZrCvtF_f9S1SB8',
    appId: '1:499282073775:android:73cf94b559afddf1b55c5a',
    messagingSenderId: '499282073775',
    projectId: 'chat-app-553db',
    storageBucket: 'chat-app-553db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjseWzgCyBzVQXxzqWg7cuTfy_hR5k_zo',
    appId: '1:499282073775:ios:f091500311ee0c50b55c5a',
    messagingSenderId: '499282073775',
    projectId: 'chat-app-553db',
    storageBucket: 'chat-app-553db.appspot.com',
    iosClientId: '499282073775-4hck91avsu87mnhld96slbpv1c6rr6eu.apps.googleusercontent.com',
    iosBundleId: 'com.example.myproject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjseWzgCyBzVQXxzqWg7cuTfy_hR5k_zo',
    appId: '1:499282073775:ios:f091500311ee0c50b55c5a',
    messagingSenderId: '499282073775',
    projectId: 'chat-app-553db',
    storageBucket: 'chat-app-553db.appspot.com',
    iosClientId: '499282073775-4hck91avsu87mnhld96slbpv1c6rr6eu.apps.googleusercontent.com',
    iosBundleId: 'com.example.myproject1',
  );
}
